apiVersion: v1
kind: Service
metadata:
  name: hostnic-svc
  namespace: kube-system
  labels:
    app: hostnic-node
spec:
  selector:
    app: hostnic-node
  ports:
    - protocol: TCP
      port: 9191         
      targetPort: 9191
      name: hostnic-metrics-port
  type: ClusterIP
  
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: hostnic
    app.kubernetes.io/vendor: kubesphere
    app.kubernetes.io/version: v1.1.0
  name: hostnic
  namespace: kube-system
spec:
  endpoints:
    - interval: 1m
      port: hostnic-metrics-port
      scheme: http
  selector:
    matchLabels:
      app: hostnic-node

---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-qke-hostnic-rules
  namespace: kubesphere-monitoring-system
spec:
  groups:
  - name: hostnic
    rules:
    - alert: hostnic-vxnet-ipam
      annotations:
        message: vxnet ip resources are not much left, the vxnet is {{ $labels.vxnet_name}}
        summary: vxnet ip lack
      expr: max(hostnic_ipam_vxnet_allocator) by(vxnet_name) / max(hostnic_ipam_vxnet_total)
        by(vxnet_name) > 0.8
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-subnet-ipam
      annotations:
        message: subnet ip resources are not much left, the subnet is {{ $labels.subnet_name}}
        summary: subnet ip lack
      expr: |
        max(hostnic_ipam_subnet_allocator) by(subnet_name) / max(hostnic_ipam_subnet_total) by(subnet_name) > 0.8
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-from-block-failed
      annotations:
        message: ipam alloc from block failed, pod in node {{ $labels.node_name}}
        summary: hostnic ipam alloc from block failed
      expr: min(irate(hostnic_ipam_alloc_from_block_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-from-host-failed
      annotations:
        message: ipam alloc from host failed, pod in node {{ $labels.node_name}}
        summary: hostnic ipam alloc from host failed
      expr: min(irate(hostnic_ipam_alloc_from_host_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-resource-notfound
      annotations:
        message: ipam resource notfound, pod in node {{ $labels.node_name}}
        summary: hostnic ipam alloc resource notfound
      expr: min(irate(hostnic_ipam_alloc_resource_notfound[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-attach-failed
      annotations:
        message: hostnic attach to vm failed, vxnet is {{ $labels.vxnet_name}}
        summary: hostnic attach failed
      expr: |
        sum(hostnic_vxnet_count{phase!="Succeeded"}) by(vxnet_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-free-from-host-failed  
      annotations:
        message: ipam free from host failed, pod in node {{ $labels.node_name}}
        summary: hostnic ipam free from host failed
      expr: min(irate(hostnic_ipam_free_from_host_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-free-from-pool-failed
      annotations:
        message: ipam free from pool failed, pod in node {{ $labels.node_name}}
        summary: hostnic ipam free from pool failed
      expr: min(irate(hostnic_ipam_free_from_pool_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-namespace-ipam
      annotations:
        message: namespace ip resources are not much left, the namespace is {{ $labels.ns_name}}
        summary: namespace ip lack
      expr: max(hostnic_ipam_namespace_allocator) by(ns_name) / max(hostnic_ipam_namespace_total)
        by(ns_name) > 0.8
      for: 5m
      labels:
        severity: warning
    - alert: hostnic-ipam-alloc-from-pool-failed
      annotations:
        message: ipam alloc from pool failed, pod in node {{ $labels.node_name}}
        summary: hostnic ipam alloc from pool failed
      expr: |
        min(irate(hostnic_ipam_alloc_from_pool_failed[5m])) by(node_name) > 0
      for: 5m
      labels:
        severity: warning